### ISSUE TITLE
SQL File and Dummy Data

### ISSUE THREAD

**Issue by nikitamalhotra** [Saqibur/Gakkou-Online-Learning#1]
Please share Dummy Data and SQL File.

**Comment by Saqibur** [comment]
I've added a sample database with some dummy data to the main repository, along with some short instructions to import the data.

[Database](https://github.com/Saqibur/Gakkou-Online-Learning/blob/master/gakkoudb.sql)

**Comment by nikitamalhotra** [comment]
Is it a complete LMS... I would like to test it....

**Comment by Saqibur** [comment]
Unfortunately not yet. There is still a major portion of the work left to be done, and it is not in a testable state. Sorry.
